export const PREDEFINED_CATEGORIES = [
  {
    id: "general",
    name: "General",
    description: "General news and global events",
  },
  {
    id: "business",
    name: "Business",
    description: "Business news, markets, and finance",
  },
  {
    id: "entertainment",
    name: "Entertainment",
    description: "Movies, TV, music, and celebrity news",
  },
  { id: "health", name: "Health", description: "Health and medical news" },
  {
    id: "science",
    name: "Science",
    description: "Scientific discoveries and research",
  },
  {
    id: "sports",
    name: "Sports",
    description: "Sports news, scores, and updates",
  },
  {
    id: "technology",
    name: "Technology",
    description: "Latest tech news, gadgets, and innovations",
  },
];

export const DEFAULT_NEWS_SOURCES = [
  {
    "id": "abc-news",
    "name": "ABC News",
    "description":
      "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
    "url": "https://abcnews.go.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://abcnews.go.com/favicon.ico",
  },
  {
    "id": "abc-news-au",
    "name": "ABC News (AU)",
    "description":
      "Australia's most trusted source of local, national and world news. Comprehensive, independent, in-depth analysis, the latest business, sport, weather and more.",
    "url": "https://www.abc.net.au/news",
    "category": "general",
    "language": "en",
    "country": "au",
    "icon": "https://www.abc.net.au/favicon.ico",
  },
  {
    "id": "ars-technica",
    "name": "Ars Technica",
    "description":
      "The PC enthusiast's resource. Power users and the tools they love, without computing religion.",
    "url": "https://arstechnica.com",
    "category": "technology",
    "language": "en",
    "country": "us",
    "icon": "https://arstechnica.com/favicon.ico",
  },
  {
    "id": "associated-press",
    "name": "Associated Press",
    "description":
      "The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.",
    "url": "https://apnews.com/",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://apnews.com/favicon.ico",
  },
  {
    "id": "australian-financial-review",
    "name": "Australian Financial Review",
    "description":
      "The Australian Financial Review reports the latest news from business, finance, investment and politics, updated in real time. It has a reputation for independent, award-winning journalism and is essential reading for the business and investor community.",
    "url": "http://www.afr.com",
    "category": "business",
    "language": "en",
    "country": "au",
    "icon": "http://www.afr.com/favicon.ico",
  },
  {
    "id": "bleacher-report",
    "name": "Bleacher Report",
    "description":
      "Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!",
    "url": "http://www.bleacherreport.com",
    "category": "sports",
    "language": "en",
    "country": "us",
    "icon": "http://www.bleacherreport.com/favicon.ico",
  },
  {
    "id": "breitbart-news",
    "name": "Breitbart News",
    "description":
      "Syndicated news and opinion website providing continuously updated headlines to top news and analysis sources.",
    "url": "http://www.breitbart.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "http://www.breitbart.com/favicon.ico",
  },
  {
    "id": "business-insider",
    "name": "Business Insider",
    "description":
      "Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.",
    "url": "http://www.businessinsider.com",
    "category": "business",
    "language": "en",
    "country": "us",
    "icon": "http://www.businessinsider.com/favicon.ico",
  },
  {
    "id": "buzzfeed",
    "name": "Buzzfeed",
    "description":
      "BuzzFeed is a cross-platform, global network for news and entertainment that generates seven billion views each month.",
    "url": "https://www.buzzfeed.com",
    "category": "entertainment",
    "language": "en",
    "country": "us",
    "icon": "https://www.buzzfeed.com/favicon.ico",
  },
  {
    "id": "cbs-news",
    "name": "CBS News",
    "description":
      "CBS News: dedicated to providing the best in journalism under standards it pioneered at the dawn of radio and television and continue in the digital age.",
    "url": "http://www.cbsnews.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "http://www.cbsnews.com/favicon.ico",
  },
  {
    "id": "cnn",
    "name": "CNN",
    "description":
      "View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN",
    "url": "http://us.cnn.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "http://us.cnn.com/favicon.ico",
  },
  {
    "id": "cnn-es",
    "name": "CNN Spanish",
    "description":
      "Lee las últimas noticias e información sobre Latinoamérica, Estados Unidos, mundo, entretenimiento, política, salud, tecnología y deportes en CNNEspañol.com.",
    "url": "http://cnnespanol.cnn.com/",
    "category": "general",
    "language": "es",
    "country": "us",
    "icon": "http://cnnespanol.cnn.com/favicon.ico",
  },
  {
    "id": "crypto-coins-news",
    "name": "Crypto Coins News",
    "description":
      "Providing breaking cryptocurrency news - focusing on Bitcoin, Ethereum, ICOs, blockchain technology, and smart contracts.",
    "url": "https://www.ccn.com",
    "category": "technology",
    "language": "en",
    "country": "us",
    "icon": "https://www.ccn.com/favicon.ico",
  },
  {
    "id": "engadget",
    "name": "Engadget",
    "description":
      "Engadget is a web magazine with obsessive daily coverage of everything new in gadgets and consumer electronics.",
    "url": "https://www.engadget.com",
    "category": "technology",
    "language": "en",
    "country": "us",
    "icon": "https://www.engadget.com/favicon.ico",
  },
  {
    "id": "entertainment-weekly",
    "name": "Entertainment Weekly",
    "description":
      "Online version of the print magazine includes entertainment news, interviews, reviews of music, film, TV and books, and a special area for magazine subscribers.",
    "url": "http://www.ew.com",
    "category": "entertainment",
    "language": "en",
    "country": "us",
    "icon": "http://www.ew.com/favicon.ico",
  },
  {
    "id": "espn",
    "name": "ESPN",
    "description":
      "ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.",
    "url": "https://www.espn.com",
    "category": "sports",
    "language": "en",
    "country": "us",
    "icon": "https://www.espn.com/favicon.ico",
  },
  {
    "id": "espn-cric-info",
    "name": "ESPN Cric Info",
    "description":
      "ESPN Cricinfo provides the most comprehensive cricket coverage available including live ball-by-ball commentary, news, unparalleled statistics, quality editorial comment and analysis.",
    "url": "http://www.espncricinfo.com/",
    "category": "sports",
    "language": "en",
    "country": "us",
    "icon": "http://www.espncricinfo.com/favicon.ico",
  },
  {
    "id": "fortune",
    "name": "Fortune",
    "description": "Fortune 500 Daily and Breaking Business News",
    "url": "http://fortune.com",
    "category": "business",
    "language": "en",
    "country": "us",
    "icon": "http://fortune.com/favicon.ico",
  },
  {
    "id": "fox-news",
    "name": "Fox News",
    "description":
      "Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.",
    "url": "http://www.foxnews.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "http://www.foxnews.com/favicon.ico",
  },
  {
    "id": "fox-sports",
    "name": "Fox Sports",
    "description":
      "Find live scores, player and team news, videos, rumors, stats, standings, schedules and fantasy games on FOX Sports.",
    "url": "http://www.foxsports.com",
    "category": "sports",
    "language": "en",
    "country": "us",
    "icon": "http://www.foxsports.com/favicon.ico",
  },
  {
    "id": "google-news",
    "name": "Google News",
    "description":
      "Comprehensive, up-to-date news coverage, aggregated from sources all over the world by Google News.",
    "url": "https://news.google.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://news.google.com/favicon.ico",
  },
  {
    "id": "google-news-au",
    "name": "Google News (Australia)",
    "description":
      "Comprehensive, up-to-date Australia news coverage, aggregated from sources all over the world by Google News.",
    "url": "https://news.google.com",
    "category": "general",
    "language": "en",
    "country": "au",
    "icon": "https://news.google.com/favicon.ico",
  },
  {
    "id": "google-news-in",
    "name": "Google News (India)",
    "description":
      "Comprehensive, up-to-date India news coverage, aggregated from sources all over the world by Google News.",
    "url": "https://news.google.com",
    "category": "general",
    "language": "en",
    "country": "in",
    "icon": "https://news.google.com/favicon.ico",
  },
  {
    "id": "mashable",
    "name": "Mashable",
    "description":
      "Mashable is a global, multi-platform media and entertainment company.",
    "url": "https://mashable.com",
    "category": "entertainment",
    "language": "en",
    "country": "us",
    "icon": "https://mashable.com/favicon.ico",
  },
  {
    "id": "medical-news-today",
    "name": "Medical News Today",
    "description":
      "Medical news and health news headlines posted throughout the day, every day.",
    "url": "http://www.medicalnewstoday.com",
    "category": "health",
    "language": "en",
    "country": "us",
    "icon": "http://www.medicalnewstoday.com/favicon.ico",
  },
  {
    "id": "msnbc",
    "name": "MSNBC",
    "description":
      "Breaking news and in-depth analysis of the headlines, as well as commentary and informed perspectives from The Rachel Maddow Show, Morning Joe & more.",
    "url": "http://www.msnbc.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "http://www.msnbc.com/favicon.ico",
  },
  {
    "id": "mtv-news",
    "name": "MTV News",
    "description":
      "The ultimate news source for music, celebrity, entertainment, movies, and current events on the web. It's pop culture on steroids.",
    "url": "http://www.mtv.com/news",
    "category": "entertainment",
    "language": "en",
    "country": "us",
    "icon": "http://www.mtv.com/favicon.ico",
  },
  {
    "id": "national-geographic",
    "name": "National Geographic",
    "description":
      "Reporting our world daily: original nature and science news from National Geographic.",
    "url": "http://news.nationalgeographic.com",
    "category": "science",
    "language": "en",
    "country": "us",
    "icon": "http://news.nationalgeographic.com/favicon.ico",
  },
  {
    "id": "national-review",
    "name": "National Review",
    "description":
      "National Review: Conservative News, Opinion, Politics, Policy, & Current Events.",
    "url": "https://www.nationalreview.com/",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://www.nationalreview.com/favicon.ico",
  },
  {
    "id": "nbc-news",
    "name": "NBC News",
    "description":
      "Breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.",
    "url": "http://www.nbcnews.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "http://www.nbcnews.com/favicon.ico",
  },
  {
    "id": "new-scientist",
    "name": "New Scientist",
    "description":
      "Breaking science and technology news from around the world. Exclusive stories and expert analysis on space, technology, health, physics, life and Earth.",
    "url": "https://www.newscientist.com/section/news",
    "category": "science",
    "language": "en",
    "country": "us",
    "icon": "https://www.newscientist.com/favicon.ico",
  },
  {
    "id": "news-com-au",
    "name": "News.com.au",
    "description":
      "We say what people are thinking and cover the issues that get people talking balancing Australian and global moments — from politics to pop culture.",
    "url": "http://www.news.com.au",
    "category": "general",
    "language": "en",
    "country": "au",
    "icon": "http://www.news.com.au/favicon.ico",
  },
  {
    "id": "newsweek",
    "name": "Newsweek",
    "description":
      "Newsweek provides in-depth analysis, news and opinion about international issues, technology, business, culture and politics.",
    "url": "https://www.newsweek.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://www.newsweek.com/favicon.ico",
  },
  {
    "id": "new-york-magazine",
    "name": "New York Magazine",
    "description":
      "NYMAG and New York magazine cover the new, the undiscovered, the next in politics, culture, food, fashion, and behavior nationally, through a New York lens.",
    "url": "https://nymag.com/",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://nymag.com/favicon.ico",
  },
  {
    "id": "next-big-future",
    "name": "Next Big Future",
    "description":
      "Coverage of science and technology that have the potential for disruption, and analysis of plans, policies, and technology that enable radical improvement.",
    "url": "https://www.nextbigfuture.com",
    "category": "science",
    "language": "en",
    "country": "us",
    "icon": "https://www.nextbigfuture.com/favicon.ico",
  },
  {
    "id": "nfl-news",
    "name": "NFL News",
    "description":
      "The official source for NFL news, schedules, stats, scores and more.",
    "url": "https://www.nfl.com",
    "category": "sports",
    "language": "en",
    "country": "us",
    "icon": "https://www.nfl.com/favicon.ico",
  },
  {
    "id": "nhl-news",
    "name": "NHL News",
    "description":
      "The most up-to-date breaking hockey news from the official source including interviews, rumors, statistics and schedules.",
    "url": "https://www.nhl.com/news",
    "category": "sports",
    "language": "en",
    "country": "us",
    "icon": "https://www.nhl.com/favicon.ico",
  },
  {
    "id": "polygon",
    "name": "Polygon",
    "description":
      "Polygon is a gaming website in partnership with Vox Media. Our culture focused site covers games, their creators, the fans, trending stories and entertainment news.",
    "url": "http://www.polygon.com",
    "category": "entertainment",
    "language": "en",
    "country": "us",
    "icon": "http://www.polygon.com/favicon.ico",
  },
  {
    "id": "recode",
    "name": "Recode",
    "description":
      "Get the latest independent tech news, reviews and analysis from Recode with the most informed and respected journalists in technology and media.",
    "url": "http://www.recode.net",
    "category": "technology",
    "language": "en",
    "country": "us",
    "icon": "http://www.recode.net/favicon.ico",
  },
  {
    "id": "reddit-r-all",
    "name": "Reddit /r/all",
    "description":
      "Reddit is an entertainment, social news networking service, and news website. Reddit's registered community members can submit content, such as text posts or direct links.",
    "url": "https://www.reddit.com/r/all",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://www.reddit.com/favicon.ico",
  },
  {
    "id": "reuters",
    "name": "Reuters",
    "description":
      "Reuters.com brings you the latest news from around the world, covering breaking news in business, politics, entertainment, technology, video and pictures.",
    "url": "https://www.reuters.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://www.reuters.com/favicon.ico",
  },
  {
    "id": "techcrunch",
    "name": "TechCrunch",
    "description":
      "TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.",
    "url": "https://techcrunch.com",
    "category": "technology",
    "language": "en",
    "country": "us",
    "icon": "https://techcrunch.com/favicon.ico",
  },
  {
    "id": "techradar",
    "name": "TechRadar",
    "description":
      "The latest technology news and reviews, covering computing, home entertainment systems, gadgets and more.",
    "url": "https://www.techradar.com",
    "category": "technology",
    "language": "en",
    "country": "us",
    "icon": "https://www.techradar.com/favicon.ico",
  },
  {
    "id": "the-american-conservative",
    "name": "The American Conservative",
    "description":
      "Realism and reform. A new voice for a new generation of conservatives.",
    "url": "http://www.theamericanconservative.com/",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "http://www.theamericanconservative.com/favicon.ico",
  },
  {
    "id": "the-hindu",
    "name": "The Hindu",
    "description":
      "The Hindu. latest news, analysis, comment, in-depth coverage of politics, business, sport, environment, cinema and arts from India's national newspaper.",
    "url": "http://www.thehindu.com",
    "category": "general",
    "language": "en",
    "country": "in",
    "icon": "http://www.thehindu.com/favicon.ico",
  },
  {
    "id": "the-next-web",
    "name": "The Next Web",
    "description":
      "The Next Web is one of the world’s largest online publications that delivers an international perspective on the latest news about Internet technology, business and culture.",
    "url": "http://thenextweb.com",
    "category": "technology",
    "language": "en",
    "country": "us",
    "icon": "http://thenextweb.com/favicon.ico",
  },
  {
    "id": "the-times-of-india",
    "name": "The Times of India",
    "description":
      "Times of India brings the Latest News and Top Breaking headlines on Politics and Current Affairs in India and around the World, Sports, Business, Bollywood News and Entertainment, Science, Technology, Health and Fitness news, Cricket and opinions from leading columnists.",
    "url": "http://timesofindia.indiatimes.com",
    "category": "general",
    "language": "en",
    "country": "in",
    "icon": "http://timesofindia.indiatimes.com/favicon.ico",
  },
  {
    "id": "the-verge",
    "name": "The Verge",
    "description":
      "The Verge covers the intersection of technology, science, art, and culture.",
    "url": "http://www.theverge.com",
    "category": "technology",
    "language": "en",
    "country": "us",
    "icon": "http://www.theverge.com/favicon.ico",
  },
  {
    "id": "the-washington-post",
    "name": "The Washington Post",
    "description":
      "Breaking news and analysis on politics, business, world national news, entertainment more. In-depth DC, Virginia, Maryland news coverage including traffic, weather, crime, education, restaurant reviews and more.",
    "url": "https://www.washingtonpost.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://www.washingtonpost.com/favicon.ico",
  },
  {
    "id": "the-washington-times",
    "name": "The Washington Times",
    "description":
      "The Washington Times delivers breaking news and commentary on the issues that affect the future of our nation.",
    "url": "https://www.washingtontimes.com/",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "https://www.washingtontimes.com/favicon.ico",
  },
  {
    "id": "time",
    "name": "Time",
    "description":
      "Breaking news and analysis from TIME.com. Politics, world news, photos, video, tech reviews, health, science and entertainment news.",
    "url": "http://time.com",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "http://time.com/favicon.ico",
  },
  {
    "id": "usa-today",
    "name": "USA Today",
    "description":
      "Get the latest national, international, and political news at USATODAY.com.",
    "url": "http://www.usatoday.com/news",
    "category": "general",
    "language": "en",
    "country": "us",
    "icon": "http://www.usatoday.com/favicon.ico",
  },
  {
    "id": "wired",
    "name": "Wired",
    "description":
      "Wired is a monthly American magazine, published in print and online editions, that focuses on how emerging technologies affect culture, the economy, and politics.",
    "url": "https://www.wired.com",
    "category": "technology",
    "language": "en",
    "country": "us",
    "icon": "https://www.wired.com/favicon.ico",
  },
  {
    "id": "others",
    "name": "Others",
    "description": "Other sources like blogs, artcles etc...",
  },
];
